### ISSUE TITLE
Lacking files(index_list) for preparing MiniImageNet dataset

### ISSUE THREAD

**Issue by SimonGrande1** [1170300714/LP-DiF#2]
Hi, thanks for the nice code.
I found there is a issue when constructing the MiniImageNet dataset.
How can we create or get the files(index_list) for consequent training.
![image](https://github.com/1170300714/LP-DiF/assets/97296260/95aa5948-b1a8-41c3-bb6b-e8b2c1549281)

**Comment by 1170300714** [comment]
收到，感谢您的来件

**Comment by 1170300714** [comment]
Thank you for your attention to our work! 

You can obtain the samples for each session from [https://github.com/xyutao/fscil/tree/master/data/index_list/mini_imagenet](https://github.com/xyutao/fscil/tree/master/data/index_list/mini_imagenet).

**Comment by SimonGrande1** [comment]
Thank you for the reply
