### ISSUE TITLE
Can you share the pretrained models for session 0?

### ISSUE THREAD

**Issue by xwf12345678** [1170300714/LP-DiF#3]
thanks for your amazing work combining CLIP and FSCIL. I can't find the pretrained models for datasets e.g. "output/LP_DiF/miniImageNet/session0/prompt_learner/model-best.pth.tar" for miniImageNet. Can you provide the pretrained models?

**Comment by 1170300714** [comment]
Of course. I will upload the model weights of the last session for evaluation its performance later. 

Additionally, sorry for there are some bugs in our startup shell script, which might require you to use the weights from session 0.

You can change ```for ((i = 1 ; i < 9 ; i++))``` to``` for ((i = 0 ; i < 9 ; i++))``` at line 2 of script_miniImageNet.sh. Then you will not meet this problem

**Comment by xwf12345678** [comment]
Thanks for your reply. Another query is that the paper describes that the model is trained in parallel with multiple cards, but the code seems to have no relevant settings. Also, please ask how the parameters including batch can be modified. Looking forward to your answer, thanks a lot!

**Comment by 1170300714** [comment]
We followed CoOp and implemented multi-GPU training using DataParallel (DP). For specific code, you can refer to lines 210-212 in trainers/lp_dif.py. 

Regarding modifying the batch size, you can adjust it by editing the following section in configs/trainers/LP_DiF/vit_b16.yaml:
```
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 50
```

Lastly, thank you very much for your attention to our humble work. If you have any further questions, please feel free to contact me at any time.

**Comment by 1170300714** [comment]
Hi, we have upload the pretrained prompt to google drive, and update the link to README. Kindly refer to these content. Thanks a lot

**Comment by xwf12345678** [comment]
Thanks for your reply again.
